# Generated by Django 6.1 on 2026-08-26 02:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Admin User',
                'verbose_name_plural': 'Master Admin Users',
                'db_table': 'master_users',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(help_text='e.g. district:create, district:approve, station:manage, case:create, case:approve', max_length=64, primary_key=True, serialize=False)),
                ('module', models.CharField(help_text='e.g. districts, stations, cases, users', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['module', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(help_text='e.g. master_admin, state_super_admin, district_admin, station_admin, officer, supervisor', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('global', 'Global Platform (Master Admin)'), ('state', 'State Level (Super Admin)'), ('district', 'District Level (District Admin)'), ('station', 'Station Level (Station Officers)')], default='station', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StateRegistry',
            fields=[
                ('state_code', models.CharField(help_text='e.g. MH, GJ, DL', max_length=10, primary_key=True, serialize=False)),
                ('state_name', models.CharField(help_text='e.g. Maharashtra', max_length=100, unique=True)),
                ('schema_name', models.CharField(help_text='PostgreSQL Schema name e.g. maharashtra', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public_master.masteruser')),
            ],
            options={
                'verbose_name': 'State Registry',
                'verbose_name_plural': 'State Registries',
                'db_table': 'states',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleMapping',
            fields=[
                ('uid', models.CharField(help_text='Unique User Identifier / Firebase UID', max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('district_id', models.CharField(blank=True, max_length=64, null=True)),
                ('station_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_master.role')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public_master.stateregistry')),
            ],
            options={
                'verbose_name': 'User Role Mapping',
                'verbose_name_plural': 'User Role Mappings',
                'db_table': 'user_role_mappings',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='public_master.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='public_master.role')),
            ],
            options={
                'verbose_name': 'Role Permission Mapping',
                'verbose_name_plural': 'Role Permission Mappings',
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
