# Generated by Django 6.1 on 2026-08-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateregistry',
            name='police_force_title',
            field=models.CharField(blank=True, help_text='e.g. Maharashtra Police', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stateregistry',
            name='super_admin_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stateregistry',
            name='super_admin_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stateregistry',
            name='super_admin_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='stateregistry',
            name='super_admin_rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
