# Generated by Django 5.2.17 on 2026-08-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
