# Generated by Django 6.1 on 2026-08-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0002_stateregistry_police_force_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('code', models.CharField(help_text='e.g. DGP, SP, PI, PSI', max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('rank_level', models.IntegerField(help_text='1 (Highest) to 12 (Lowest)')),
                ('can_approve_transfers', models.BooleanField(default=False)),
                ('can_manage_all_cases', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Police Designation',
                'verbose_name_plural': 'Police Designations',
                'db_table': 'designations',
                'ordering': ['rank_level', 'code'],
            },
        ),
    ]
