# Generated by Django 6.1 on 2026-08-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0003_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masteruser',
            name='firebase_uid',
        ),
        migrations.AlterField(
            model_name='userrolemapping',
            name='uid',
            field=models.CharField(help_text='Unique User Identifier', max_length=128, primary_key=True, serialize=False),
        ),
    ]
