# Generated by Django 6.1 on 2026-08-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0004_remove_masteruser_firebase_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='is_district_admin_allowed',
            field=models.BooleanField(default=False, help_text='Allowed as District Admin'),
        ),
        migrations.AddField(
            model_name='designation',
            name='is_division_admin_allowed',
            field=models.BooleanField(default=False, help_text='Allowed as Division Admin'),
        ),
        migrations.AddField(
            model_name='designation',
            name='is_state_admin_allowed',
            field=models.BooleanField(default=False, help_text='Allowed as State Super Admin'),
        ),
        migrations.AddField(
            model_name='designation',
            name='is_station_admin_allowed',
            field=models.BooleanField(default=False, help_text='Allowed as Station Admin / SHO'),
        ),
    ]
