# Generated by Django 6.1 on 2026-08-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0005_designation_is_district_admin_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateregistry',
            name='department_logo_url',
            field=models.TextField(blank=True, help_text='State Police Department PNG Logo URL or Base64 Image Data', null=True),
        ),
    ]
