# Generated by Django 6.1 on 2026-08-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0006_stateregistry_department_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='allowed_admin_roles',
            field=models.JSONField(default=list, help_text="[], ['station_admin'], ['district_admin'], ['division_admin']"),
        ),
        migrations.AddField(
            model_name='designation',
            name='allowed_categories',
            field=models.JSONField(default=list, help_text="['field_officer'] or ['field_officer', 'admin_officer']"),
        ),
        migrations.AddField(
            model_name='designation',
            name='approving_authority',
            field=models.CharField(default='station_admin', max_length=64),
        ),
        migrations.AddField(
            model_name='designation',
            name='display_name',
            field=models.CharField(blank=True, help_text='e.g. Naik Police Constable (NPC)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='implied_unit_type',
            field=models.CharField(blank=True, help_text='Commissionerate Police or Superintendent Police (Rural)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='required_hierarchy_level',
            field=models.CharField(default='station', help_text='station, district, division, state', max_length=32),
        ),
        migrations.AddField(
            model_name='designation',
            name='role_type',
            field=models.CharField(default='staff_only', help_text='staff_only, dual_role, state_hq_only', max_length=32),
        ),
        migrations.AlterField(
            model_name='designation',
            name='code',
            field=models.CharField(help_text='e.g. PC, NPC, HC, ASI, PSI, API, PI, SP, DIG, DGP', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designation',
            name='rank_level',
            field=models.IntegerField(help_text='1 (Highest - DGP) to 12 (Lowest - PC)'),
        ),
    ]
