# Generated by Django 6.1 on 2026-08-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0007_designation_allowed_admin_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAnnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='gavel_rounded', max_length=64)),
                ('icon_color_hex', models.CharField(default='0xFF0A2540', max_length=16)),
                ('tag', models.CharField(default='LAW & ORDER', max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_announcements',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterDivision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state_code', models.CharField(db_index=True, default='MH', max_length=10)),
                ('state_name', models.CharField(default='Maharashtra', max_length=100)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Master Division',
                'verbose_name_plural': 'Master Divisions',
                'db_table': 'master_divisions',
                'ordering': ['state_code', 'name'],
                'unique_together': {('state_code', 'name')},
            },
        ),
    ]
