# Generated by Django 5.2.17 on 2026-09-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0002_masteruser_firebase_uid'),
        ('public_master', '0008_appannouncement_masterdivision'),
    ]

    operations = [
    ]
