# Generated by Django 6.1 on 2026-09-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0008_appannouncement_masterdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateregistry',
            name='super_admin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stateregistry',
            name='super_admin_rank',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
