# Generated by Django 6.1 on 2026-10-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_master', '0013_ensure_maharashtra_master_divisions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterdivision',
            options={'ordering': ['state_code', 'name'], 'verbose_name': 'Master Division (Tenant-Scoped)', 'verbose_name_plural': 'Master Divisions (Tenant-Scoped)'},
        ),
    ]
