# Generated by Django 6.1 on 2026-08-26 02:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('module_key', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('case_number', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('complainant', models.CharField(blank=True, max_length=255)),
                ('accused', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=32)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Disposal', 'Disposal'), ('Closed', 'Closed'), ('Open', 'Open')], db_index=True, default='Pending', max_length=32)),
                ('assigned_officer', models.CharField(blank=True, max_length=255)),
                ('assigned_officer_uid', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.CharField(blank=True, max_length=128)),
                ('station_name', models.CharField(db_index=True, max_length=255)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case Record',
                'verbose_name_plural': 'Case Records',
                'db_table': 'cases_caserecord',
                'ordering': ['-created_at'],
            },
        ),
    ]
