# Generated by Django 6.1.1 on 2026-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='disposal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
