# Generated by Django 6.1.1 on 2026-10-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caserecord_disposal_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caserecord',
            name='disposal_date',
        ),
    ]
