# Generated by Django 6.1.1 on 2026-10-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_caserecord_disposal_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caserecord',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Case Record', 'verbose_name_plural': 'Case Records'},
        ),
    ]
