# Generated by Django 6.1.1 on 2026-10-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_caserecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Detected', 'Detected'), ('Disposal', 'Disposal'), ('Closed', 'Closed'), ('Open', 'Open')], db_index=True, default='Pending', max_length=32),
        ),
    ]
