# Generated by Django 6.1 on 2026-08-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('uid', models.CharField(help_text='Firebase Auth UID', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('badge_number', models.CharField(blank=True, max_length=64)),
                ('designation', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('station_name', models.CharField(blank=True, max_length=255)),
                ('station_address', models.TextField(blank=True)),
                ('station_landline', models.CharField(blank=True, max_length=32)),
                ('govt_id', models.CharField(blank=True, max_length=64)),
                ('photo_url', models.URLField(blank=True, max_length=1024)),
                ('id_card_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('role', models.CharField(choices=[('officer', 'Officer'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='officer', max_length=32)),
                ('additional_stations', models.JSONField(blank=True, default=list)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected')], default='active', max_length=32)),
                ('district', models.CharField(blank=True, max_length=128, null=True)),
                ('zone', models.CharField(blank=True, max_length=128, null=True)),
                ('station_case_view_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Officer Profile',
                'verbose_name_plural': 'Officer Profiles',
                'db_table': 'users_officerprofile',
                'ordering': ['-created_at'],
            },
        ),
    ]
