# Generated by Django 6.1 on 2026-08-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officerprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='district_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for primary backend login', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='role_id',
            field=models.CharField(default='officer', help_text='Dynamic Role ID referencing public.roles', max_length=64),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='station_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='uid',
            field=models.CharField(help_text='Unique Officer Identifier / Firebase UID', max_length=128, primary_key=True, serialize=False),
        ),
    ]
