# Generated by Django 6.1 on 2026-08-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_officerprofile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_role_id', models.CharField(blank=True, help_text='e.g. station_head, district_admin, state_super_admin, master_admin', max_length=64)),
                ('target_station_name', models.CharField(blank=True, help_text='Strict ABAC filter: ONLY notify head of THIS station', max_length=255, null=True)),
                ('target_district', models.CharField(blank=True, help_text='Strict ABAC filter: ONLY notify admin of THIS district', max_length=128, null=True)),
                ('target_state_code', models.CharField(blank=True, help_text='Filter to state admin', max_length=10, null=True)),
                ('target_user_uid', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(default='approval_request', max_length=64)),
                ('registration_uid', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_notificationrecord',
                'ordering': ['-created_at'],
            },
        ),
    ]
