# Generated by Django 6.1 on 2026-08-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_officerprofile_age_officerprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerprofile',
            name='uid',
            field=models.CharField(help_text='Unique Officer Identifier', max_length=128, primary_key=True, serialize=False),
        ),
    ]
