# Generated by Django 6.1 on 2026-08-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_officerprofile_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('requested_by_uid', models.CharField(db_index=True, max_length=128)),
                ('officer_name', models.CharField(blank=True, max_length=255)),
                ('from_designation', models.CharField(blank=True, max_length=128)),
                ('to_designation', models.CharField(blank=True, max_length=128)),
                ('from_station_name', models.CharField(blank=True, max_length=255)),
                ('to_station_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('from_district', models.CharField(blank=True, max_length=128)),
                ('to_district', models.CharField(blank=True, db_index=True, max_length=128)),
                ('from_state', models.CharField(blank=True, max_length=128)),
                ('to_state', models.CharField(blank=True, max_length=128)),
                ('from_unit_type', models.CharField(blank=True, max_length=128)),
                ('to_unit_type', models.CharField(blank=True, max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=32)),
                ('approved_by_uid', models.CharField(blank=True, max_length=128, null=True)),
                ('rejected_by_uid', models.CharField(blank=True, max_length=128, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_transferrequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
