# Generated by Django 6.1 on 2026-08-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_transferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='division_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='division_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
