# Generated by Django 6.1 on 2026-08-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_officerprofile_division_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='is_biometric_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
