# Generated by Django 6.1 on 2026-08-29 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(db_index=True, max_length=128)),
                ('uid', models.CharField(db_index=True, default='anonymous', max_length=128)),
                ('platform', models.CharField(default='unknown', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'core_auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SosAlert',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('officer_id', models.CharField(db_index=True, max_length=128)),
                ('officer_name', models.CharField(blank=True, max_length=255)),
                ('seva_number', models.CharField(blank=True, max_length=64)),
                ('designation', models.CharField(blank=True, max_length=128)),
                ('station_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('district', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE_DURESS', 'Active Duress'), ('RESOLVED', 'Resolved')], db_index=True, default='ACTIVE_DURESS', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('maps_url', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_by_uid', models.CharField(blank=True, max_length=128, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'core_sosalert',
                'ordering': ['-created_at'],
            },
        ),
    ]
