# Generated by Django 6.1 on 2026-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='category',
            field=models.CharField(db_index=True, default='general', help_text='auth, case, admin, security, system', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='district_name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='division_name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='station_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='platform',
            field=models.CharField(default='web', max_length=32),
        ),
    ]
