# Generated by Django 6.1 on 2026-09-21 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0002_alter_casecategory_category_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, db_column='parent_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_subcategories', to='crimetab.casecategory'),
        ),
    ]
