# Generated by Django 6.1 for PMS Common Form Final Rebuild
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

SQL_CREATE_TABLES = """
CREATE SCHEMA IF NOT EXISTS maharashtra;
SET search_path TO maharashtra, public;

CREATE TABLE IF NOT EXISTS crime_registration_info (
    case_id             VARCHAR(128) PRIMARY KEY REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    cr_number           VARCHAR(30),
    registered_datetime TIMESTAMPTZ,
    is_unknown_accused  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS acts (
    act_id          BIGSERIAL PRIMARY KEY,
    act_name        VARCHAR(100) NOT NULL,
    display_order   INT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS act_sections (
    section_id      BIGSERIAL PRIMARY KEY,
    act_id          BIGINT NOT NULL REFERENCES acts(act_id) ON DELETE CASCADE,
    section_number  VARCHAR(10) NOT NULL,
    section_title   VARCHAR(255) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (act_id, section_number)
);

CREATE TABLE IF NOT EXISTS act_subsections (
    subsection_id   BIGSERIAL PRIMARY KEY,
    section_id      BIGINT NOT NULL REFERENCES act_sections(section_id) ON DELETE CASCADE,
    subsection_code VARCHAR(20) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (section_id, subsection_code)
);

CREATE TABLE IF NOT EXISTS crime_case_acts_sections (
    charge_id       BIGSERIAL PRIMARY KEY,
    case_id         VARCHAR(128) NOT NULL REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    act_id          BIGINT NOT NULL REFERENCES acts(act_id) ON DELETE CASCADE,
    section_id      BIGINT NOT NULL REFERENCES act_sections(section_id) ON DELETE CASCADE,
    subsection_id   BIGINT REFERENCES act_subsections(subsection_id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_charges_case ON crime_case_acts_sections(case_id);
CREATE INDEX IF NOT EXISTS idx_charges_section ON crime_case_acts_sections(section_id);

CREATE TABLE IF NOT EXISTS crime_spot (
    case_id              VARCHAR(128) PRIMARY KEY REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    village_town         VARCHAR(100),
    area_name            VARCHAR(100),
    full_address         TEXT,
    occurrence_datetime  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS cases_person (
    person_id           BIGSERIAL PRIMARY KEY,
    case_id             VARCHAR(128) NOT NULL REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    role                VARCHAR(20) NOT NULL CHECK (role IN (
                            'complainant', 'accused', 'suspected_accused', 'unidentified_accused'
                        )),
    name                VARCHAR(150),
    age                 INTEGER,
    gender              VARCHAR(10),
    occupation          VARCHAR(100),
    mobile              VARCHAR(10),
    aadhaar             VARCHAR(12),
    pan                 VARCHAR(10),
    religion            VARCHAR(50),
    caste               VARCHAR(50),
    address             TEXT,
    approximate_age         VARCHAR(20),
    skin_colour              VARCHAR(50),
    possible_occupation       VARCHAR(100),
    identification_mark        TEXT,
    height                       VARCHAR(20),
    description                    TEXT,
    created_at                        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_person_case ON cases_person(case_id);
CREATE INDEX IF NOT EXISTS idx_person_case_role ON cases_person(case_id, role);

CREATE TABLE IF NOT EXISTS crime_case_responsibility (
    case_id                   VARCHAR(128) PRIMARY KEY REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    io_name                   VARCHAR(150),
    io_designation            VARCHAR(20),
    registered_by_name        VARCHAR(150),
    registered_by_designation VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS arrest_release_status (
    arrest_id                  BIGSERIAL PRIMARY KEY,
    person_id                  BIGINT NOT NULL UNIQUE REFERENCES cases_person(person_id) ON DELETE CASCADE,
    arrest_datetime             TIMESTAMPTZ,
    sec_47_48_bnss                BOOLEAN,
    relative_friend_name            VARCHAR(150),
    relative_friend_relation          VARCHAR(50),
    release_on_notice                    BOOLEAN,
    release_on_notice_datetime             TIMESTAMPTZ,
    anticipatory_bail                        BOOLEAN,
    anticipatory_bail_datetime                 TIMESTAMPTZ,
    death_of_accused                             BOOLEAN,
    death_of_accused_datetime                      TIMESTAMPTZ,
    created_at                                       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS remand_custody (
    remand_id       BIGSERIAL PRIMARY KEY,
    person_id       BIGINT NOT NULL UNIQUE REFERENCES cases_person(person_id) ON DELETE CASCADE,
    pcr_days        INTEGER,
    mcr             BOOLEAN,
    pr_bond         BOOLEAN,
    bail            BOOLEAN,
    surety_name     VARCHAR(150),
    jail             BOOLEAN,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_pr_bond_requires_mcr CHECK (
        pr_bond IS NOT TRUE OR mcr IS TRUE
    ),
    CONSTRAINT chk_surety_jail_requires_bail CHECK (
        (surety_name IS NULL AND jail IS NOT TRUE) OR bail IS TRUE
    )
);

CREATE TABLE IF NOT EXISTS cctv_technical (
    case_id             VARCHAR(128) PRIMARY KEY REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    cctv_checked        BOOLEAN,
    cdr_sent_date       DATE,
    cdr_received_date   DATE
);

CREATE TABLE IF NOT EXISTS procedural_checklist (
    checklist_id     BIGSERIAL PRIMARY KEY,
    case_id          VARCHAR(128) NOT NULL REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    item_name        VARCHAR(40) NOT NULL CHECK (item_name IN (
                        'Spot Panchanama', 'Seizure Panchanama', 'Search Panchanama',
                        'Personal Search Panchanama', 'Memorandum Panchanama',
                        'Identification Panchanama', 'Identification Parade Panchanama'
                    )),
    is_checked       BOOLEAN NOT NULL DEFAULT FALSE,
    event_datetime   TIMESTAMPTZ,
    UNIQUE (case_id, item_name)
);

CREATE TABLE IF NOT EXISTS case_forensics (
    case_id              VARCHAR(128) PRIMARY KEY REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    e_shakshya           BOOLEAN,
    fingerprint_taken    BOOLEAN,
    nafis_fingerprint    BOOLEAN
);

CREATE TABLE IF NOT EXISTS seizure_records (
    seizure_id      BIGSERIAL PRIMARY KEY,
    case_id         VARCHAR(128) NOT NULL REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    description     TEXT NOT NULL,
    name            VARCHAR(150),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS preventive_action_items (
    item_id          BIGSERIAL PRIMARY KEY,
    case_id          VARCHAR(128) NOT NULL REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    action_type      VARCHAR(30) NOT NULL CHECK (action_type IN (
                        '107 CrPC/126 BNSS', '109 CrPC/128 BNSS', '110 CrPC/129 BNSS',
                        '151(3) CrPC/170 BNSS', '144 CrPC/163 BNSS', '149 CrPC/168 BNSS',
                        '55 MPA', '56 MPA', '57 MPA', '122 MPA', '93 Prohibition Act'
                    )),
    action_date      DATE NOT NULL,
    outward_number   VARCHAR(50),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (case_id, action_type)
);

CREATE TABLE IF NOT EXISTS preventive_bond (
    case_id                 VARCHAR(128) PRIMARY KEY REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    bond_date               DATE,
    bond_cancellation_date  DATE
);

CREATE TABLE IF NOT EXISTS discharge_status (
    person_id        BIGINT PRIMARY KEY REFERENCES cases_person(person_id) ON DELETE CASCADE,
    is_discharged    BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS scrutiny_pipeline (
    case_id                VARCHAR(128) PRIMARY KEY REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    sdpo_acp_send_date     DATE,
    sdpo_acp_grant_date    DATE,
    addl_sp_dcp_send_date  DATE,
    addl_sp_dcp_grant_date DATE,
    addl_cp_send_date      DATE,
    addl_cp_grant_date     DATE,
    app_send_date          DATE,
    app_grant_date         DATE
);

CREATE TABLE IF NOT EXISTS final_verdict (
    case_id                     VARCHAR(128) PRIMARY KEY REFERENCES cases_caserecord(id) ON DELETE CASCADE,
    charge_sheet_no             VARCHAR(50),
    a_final_number              VARCHAR(50),
    b_final_number              VARCHAR(50),
    c_final_number              VARCHAR(50),
    nc_final_number             VARCHAR(50),
    abeted_summary_no           VARCHAR(50),
    stay_by_high_court_date     DATE,
    quashed_by_high_court_date  DATE
);

-- Ensure all altered columns exist on previously created tables
ALTER TABLE crime_registration_info ADD COLUMN IF NOT EXISTS cr_number VARCHAR(30);
ALTER TABLE crime_registration_info ADD COLUMN IF NOT EXISTS is_unknown_accused BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE crime_registration_info ADD COLUMN IF NOT EXISTS registered_datetime TIMESTAMPTZ;

ALTER TABLE cases_person ADD COLUMN IF NOT EXISTS approximate_age VARCHAR(20);
ALTER TABLE cases_person ADD COLUMN IF NOT EXISTS skin_colour VARCHAR(50);
ALTER TABLE cases_person ADD COLUMN IF NOT EXISTS possible_occupation VARCHAR(100);
ALTER TABLE cases_person ADD COLUMN IF NOT EXISTS identification_mark TEXT;
ALTER TABLE cases_person ADD COLUMN IF NOT EXISTS height VARCHAR(20);
ALTER TABLE cases_person ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE cases_person ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE seizure_records ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE seizure_records ADD COLUMN IF NOT EXISTS name VARCHAR(150);

ALTER TABLE arrest_release_status ADD COLUMN IF NOT EXISTS relative_friend_name VARCHAR(150);
ALTER TABLE arrest_release_status ADD COLUMN IF NOT EXISTS relative_friend_relation VARCHAR(50);
ALTER TABLE arrest_release_status ADD COLUMN IF NOT EXISTS release_on_notice BOOLEAN;
ALTER TABLE arrest_release_status ADD COLUMN IF NOT EXISTS release_on_notice_datetime TIMESTAMPTZ;
ALTER TABLE arrest_release_status ADD COLUMN IF NOT EXISTS sec_47_48_bnss BOOLEAN;
ALTER TABLE arrest_release_status ADD COLUMN IF NOT EXISTS anticipatory_bail BOOLEAN;
ALTER TABLE arrest_release_status ADD COLUMN IF NOT EXISTS anticipatory_bail_datetime TIMESTAMPTZ;
ALTER TABLE arrest_release_status ADD COLUMN IF NOT EXISTS arrest_datetime TIMESTAMPTZ;
ALTER TABLE arrest_release_status ADD COLUMN IF NOT EXISTS death_of_accused BOOLEAN;
ALTER TABLE arrest_release_status ADD COLUMN IF NOT EXISTS death_of_accused_datetime TIMESTAMPTZ;

ALTER TABLE acts ADD COLUMN IF NOT EXISTS display_order INT;
ALTER TABLE act_sections ADD COLUMN IF NOT EXISTS section_title VARCHAR(255) DEFAULT '';
ALTER TABLE crime_spot ADD COLUMN IF NOT EXISTS occurrence_datetime TIMESTAMPTZ;

ALTER TABLE final_verdict ADD COLUMN IF NOT EXISTS a_final_number VARCHAR(50);
ALTER TABLE final_verdict ADD COLUMN IF NOT EXISTS abeted_summary_no VARCHAR(50);
ALTER TABLE final_verdict ADD COLUMN IF NOT EXISTS b_final_number VARCHAR(50);
ALTER TABLE final_verdict ADD COLUMN IF NOT EXISTS c_final_number VARCHAR(50);
ALTER TABLE final_verdict ADD COLUMN IF NOT EXISTS charge_sheet_no VARCHAR(50);
ALTER TABLE final_verdict ADD COLUMN IF NOT EXISTS nc_final_number VARCHAR(50);
ALTER TABLE final_verdict ADD COLUMN IF NOT EXISTS quashed_by_high_court_date DATE;
ALTER TABLE final_verdict ADD COLUMN IF NOT EXISTS stay_by_high_court_date DATE;

ALTER TABLE scrutiny_pipeline ADD COLUMN IF NOT EXISTS addl_cp_grant_date DATE;
ALTER TABLE scrutiny_pipeline ADD COLUMN IF NOT EXISTS addl_cp_send_date DATE;
ALTER TABLE scrutiny_pipeline ADD COLUMN IF NOT EXISTS addl_sp_dcp_grant_date DATE;
ALTER TABLE scrutiny_pipeline ADD COLUMN IF NOT EXISTS addl_sp_dcp_send_date DATE;
ALTER TABLE scrutiny_pipeline ADD COLUMN IF NOT EXISTS sdpo_acp_grant_date DATE;
ALTER TABLE scrutiny_pipeline ADD COLUMN IF NOT EXISTS sdpo_acp_send_date DATE;

DELETE FROM section_field_templates WHERE section_id NOT IN (SELECT section_id FROM act_sections);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('crimetab', '0003_casecategory_parent_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=SQL_CREATE_TABLES,
                    reverse_sql=""
                ),
            ],
            state_operations=[
                # Remove obsolete fields from 0001 models
                migrations.RemoveField(model_name='arrestreleasestatus', name='arrest_date_time'),
                migrations.RemoveField(model_name='arrestreleasestatus', name='arresting_officer'),
                migrations.RemoveField(model_name='arrestreleasestatus', name='case'),
                migrations.RemoveField(model_name='arrestreleasestatus', name='notice_date'),
                migrations.RemoveField(model_name='arrestreleasestatus', name='notice_issued'),
                migrations.RemoveField(model_name='arrestreleasestatus', name='relative_name'),
                migrations.RemoveField(model_name='arrestreleasestatus', name='relative_relation'),
                migrations.RemoveField(model_name='arrestreleasestatus', name='release_date'),
                migrations.RemoveField(model_name='arrestreleasestatus', name='release_type'),
                migrations.RemoveField(model_name='arrestreleasestatus', name='released_on_notice'),
                migrations.RemoveField(model_name='arrestreleasestatus', name='wanted_status'),
                migrations.RemoveField(model_name='casesperson', name='death_date_time'),
                migrations.RemoveField(model_name='casesperson', name='death_place'),
                migrations.RemoveField(model_name='casesperson', name='identification_markers'),
                migrations.RemoveField(model_name='casesperson', name='inquest_details'),
                migrations.RemoveField(model_name='casesperson', name='is_died'),
                migrations.RemoveField(model_name='casesperson', name='medical_exam_details'),
                migrations.RemoveField(model_name='casesperson', name='medical_exam_done'),
                migrations.RemoveField(model_name='casesperson', name='skin_color'),
                migrations.RemoveField(model_name='casesperson', name='statement_details'),
                migrations.RemoveField(model_name='crimecaseactssections', name='id'),
                migrations.RemoveField(model_name='crimecaseactssections', name='is_major'),
                migrations.RemoveField(model_name='crimecaseresponsibility', name='cctv_available'),
                migrations.RemoveField(model_name='crimecaseresponsibility', name='cctv_date_time'),
                migrations.RemoveField(model_name='crimecaseresponsibility', name='created_at'),
                migrations.RemoveField(model_name='crimecaseresponsibility', name='resp_id'),
                migrations.RemoveField(model_name='crimeregistrationinfo', name='brief_description'),
                migrations.RemoveField(model_name='crimeregistrationinfo', name='cr_no'),
                migrations.RemoveField(model_name='crimeregistrationinfo', name='fir_copy_path'),
                migrations.RemoveField(model_name='crimeregistrationinfo', name='info_id'),
                migrations.RemoveField(model_name='crimeregistrationinfo', name='reg_date'),
                migrations.RemoveField(model_name='crimespot', name='created_at'),
                migrations.RemoveField(model_name='crimespot', name='latitude'),
                migrations.RemoveField(model_name='crimespot', name='longitude'),
                migrations.RemoveField(model_name='crimespot', name='spot_id'),
                migrations.RemoveField(model_name='dischargestatus', name='case'),
                migrations.RemoveField(model_name='dischargestatus', name='created_at'),
                migrations.RemoveField(model_name='dischargestatus', name='discharge_date'),
                migrations.RemoveField(model_name='dischargestatus', name='discharge_id'),
                migrations.RemoveField(model_name='dischargestatus', name='discharge_reason'),
                migrations.RemoveField(model_name='finalverdict', name='cc_st_number'),
                migrations.RemoveField(model_name='finalverdict', name='created_at'),
                migrations.RemoveField(model_name='finalverdict', name='final_summary'),
                migrations.RemoveField(model_name='finalverdict', name='is_quashed'),
                migrations.RemoveField(model_name='finalverdict', name='person'),
                migrations.RemoveField(model_name='finalverdict', name='quashed_date'),
                migrations.RemoveField(model_name='finalverdict', name='sentence_details'),
                migrations.RemoveField(model_name='finalverdict', name='verdict_date'),
                migrations.RemoveField(model_name='finalverdict', name='verdict_id'),
                migrations.RemoveField(model_name='finalverdict', name='verdict_status'),
                migrations.RemoveField(model_name='scrutinypipeline', name='app_remarks'),
                migrations.RemoveField(model_name='scrutinypipeline', name='created_at'),
                migrations.RemoveField(model_name='scrutinypipeline', name='dcp_grant_date'),
                migrations.RemoveField(model_name='scrutinypipeline', name='dcp_remarks'),
                migrations.RemoveField(model_name='scrutinypipeline', name='dcp_send_date'),
                migrations.RemoveField(model_name='scrutinypipeline', name='scrutiny_id'),
                migrations.RemoveField(model_name='scrutinypipeline', name='sdpo_grant_date'),
                migrations.RemoveField(model_name='scrutinypipeline', name='sdpo_remarks'),
                migrations.RemoveField(model_name='scrutinypipeline', name='sdpo_send_date'),
                migrations.DeleteModel(name='CaseTransfer'),
                migrations.DeleteModel(name='CourtFiling'),
                migrations.DeleteModel(name='PreventiveAction'),
                migrations.DeleteModel(name='ProceduralDetails'),
                migrations.DeleteModel(name='RecoveredProperty'),
                migrations.DeleteModel(name='SeizureRecord'),
                migrations.DeleteModel(name='StolenProperty'),
                migrations.DeleteModel(name='TechnicalCustody'),

                # Create newly added models
                migrations.CreateModel(
                    name='CaseForensics',
                    fields=[
                        ('case', models.OneToOneField(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='forensics', serialize=False, to='cases.caserecord')),
                        ('e_shakshya', models.BooleanField(blank=True, null=True)),
                        ('fingerprint_taken', models.BooleanField(blank=True, null=True)),
                        ('nafis_fingerprint', models.BooleanField(blank=True, null=True)),
                    ],
                    options={'verbose_name': 'Case Forensics', 'verbose_name_plural': 'Case Forensics', 'db_table': 'case_forensics'},
                ),
                migrations.CreateModel(
                    name='CctvTechnical',
                    fields=[
                        ('case', models.OneToOneField(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cctv_technical', serialize=False, to='cases.caserecord')),
                        ('cctv_checked', models.BooleanField(blank=True, null=True)),
                        ('cdr_sent_date', models.DateField(blank=True, null=True)),
                        ('cdr_received_date', models.DateField(blank=True, null=True)),
                    ],
                    options={'verbose_name': 'CCTV Technical', 'verbose_name_plural': 'CCTV Technicals', 'db_table': 'cctv_technical'},
                ),
                migrations.CreateModel(
                    name='PreventiveActionItems',
                    fields=[
                        ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('action_type', models.CharField(choices=[('107 CrPC/126 BNSS', '107 CrPC/126 BNSS'), ('109 CrPC/128 BNSS', '109 CrPC/128 BNSS'), ('110 CrPC/129 BNSS', '110 CrPC/129 BNSS'), ('151(3) CrPC/170 BNSS', '151(3) CrPC/170 BNSS'), ('144 CrPC/163 BNSS', '144 CrPC/163 BNSS'), ('149 CrPC/168 BNSS', '149 CrPC/168 BNSS'), ('55 MPA', '55 MPA'), ('56 MPA', '56 MPA'), ('57 MPA', '57 MPA'), ('122 MPA', '122 MPA'), ('93 Prohibition Act', '93 Prohibition Act')], default='107 CrPC/126 BNSS', max_length=30)),
                        ('action_date', models.DateField(default=django.utils.timezone.now)),
                        ('outward_number', models.CharField(blank=True, max_length=50, null=True)),
                        ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                        ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='preventive_action_items', to='cases.caserecord')),
                    ],
                    options={'verbose_name': 'Preventive Action Item', 'verbose_name_plural': 'Preventive Action Items', 'db_table': 'preventive_action_items', 'unique_together': {('case', 'action_type')}},
                ),
                migrations.CreateModel(
                    name='PreventiveBond',
                    fields=[
                        ('case', models.OneToOneField(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preventive_bond', serialize=False, to='cases.caserecord')),
                        ('bond_date', models.DateField(blank=True, null=True)),
                        ('bond_cancellation_date', models.DateField(blank=True, null=True)),
                    ],
                    options={'verbose_name': 'Preventive Bond', 'verbose_name_plural': 'Preventive Bonds', 'db_table': 'preventive_bond'},
                ),
                migrations.CreateModel(
                    name='ProceduralChecklist',
                    fields=[
                        ('checklist_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('item_name', models.CharField(choices=[('Spot Panchanama', 'Spot Panchanama'), ('Seizure Panchanama', 'Seizure Panchanama'), ('Search Panchanama', 'Search Panchanama'), ('Personal Search Panchanama', 'Personal Search Panchanama'), ('Memorandum Panchanama', 'Memorandum Panchanama'), ('Identification Panchanama', 'Identification Panchanama'), ('Identification Parade Panchanama', 'Identification Parade Panchanama')], default='Spot Panchanama', max_length=40)),
                        ('is_checked', models.BooleanField(default=False)),
                        ('event_datetime', models.DateTimeField(blank=True, null=True)),
                        ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='procedural_checklists', to='cases.caserecord')),
                    ],
                    options={'verbose_name': 'Procedural Checklist', 'verbose_name_plural': 'Procedural Checklists', 'db_table': 'procedural_checklist', 'unique_together': {('case', 'item_name')}},
                ),
                migrations.CreateModel(
                    name='RemandCustody',
                    fields=[
                        ('remand_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('pcr_days', models.IntegerField(blank=True, null=True)),
                        ('mcr', models.BooleanField(blank=True, null=True)),
                        ('pr_bond', models.BooleanField(blank=True, null=True)),
                        ('bail', models.BooleanField(blank=True, null=True)),
                        ('surety_name', models.CharField(blank=True, max_length=150, null=True)),
                        ('jail', models.BooleanField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                        ('person', models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, related_name='remand_custody', to='crimetab.casesperson')),
                    ],
                    options={'verbose_name': 'Remand Custody', 'verbose_name_plural': 'Remand Custodies', 'db_table': 'remand_custody'},
                ),
                migrations.CreateModel(
                    name='SeizureRecords',
                    fields=[
                        ('seizure_id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('description', models.TextField(default='')),
                        ('name', models.CharField(blank=True, max_length=150, null=True)),
                        ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                        ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='seizures', to='cases.caserecord')),
                    ],
                    options={'verbose_name': 'Seizure Record', 'verbose_name_plural': 'Seizure Records', 'db_table': 'seizure_records'},
                ),

                # Add and alter fields for updated models
                migrations.AddField(model_name='act', name='display_order', field=models.IntegerField(blank=True, null=True)),
                migrations.AddField(model_name='actsection', name='section_title', field=models.CharField(default='', max_length=255)),
                migrations.AddField(model_name='arrestreleasestatus', name='anticipatory_bail', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='arrestreleasestatus', name='anticipatory_bail_datetime', field=models.DateTimeField(blank=True, null=True)),
                migrations.AddField(model_name='arrestreleasestatus', name='arrest_datetime', field=models.DateTimeField(blank=True, null=True)),
                migrations.AddField(model_name='arrestreleasestatus', name='death_of_accused', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='arrestreleasestatus', name='death_of_accused_datetime', field=models.DateTimeField(blank=True, null=True)),
                migrations.AddField(model_name='arrestreleasestatus', name='relative_friend_name', field=models.CharField(blank=True, max_length=150, null=True)),
                migrations.AddField(model_name='arrestreleasestatus', name='relative_friend_relation', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='arrestreleasestatus', name='release_on_notice', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='arrestreleasestatus', name='release_on_notice_datetime', field=models.DateTimeField(blank=True, null=True)),
                migrations.AddField(model_name='arrestreleasestatus', name='sec_47_48_bnss', field=models.BooleanField(blank=True, null=True)),
                migrations.AddField(model_name='casesperson', name='approximate_age', field=models.CharField(blank=True, max_length=20, null=True)),
                migrations.AddField(model_name='casesperson', name='description', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='casesperson', name='height', field=models.CharField(blank=True, max_length=20, null=True)),
                migrations.AddField(model_name='casesperson', name='identification_mark', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='casesperson', name='possible_occupation', field=models.CharField(blank=True, max_length=100, null=True)),
                migrations.AddField(model_name='casesperson', name='skin_colour', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='casesperson', name='updated_at', field=models.DateTimeField(default=django.utils.timezone.now)),
                migrations.AddField(model_name='crimecaseactssections', name='charge_id', field=models.BigAutoField(default=1, primary_key=True, serialize=False), preserve_default=False),
                migrations.AddField(model_name='crimecaseactssections', name='subsection', field=models.ForeignKey(blank=True, db_column='subsection_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_charges', to='crimetab.actsubsection')),
                migrations.AddField(model_name='crimeregistrationinfo', name='cr_number', field=models.CharField(blank=True, max_length=30, null=True)),
                migrations.AddField(model_name='crimeregistrationinfo', name='is_unknown_accused', field=models.BooleanField(default=False)),
                migrations.AddField(model_name='crimeregistrationinfo', name='registered_datetime', field=models.DateTimeField(blank=True, null=True)),
                migrations.AddField(model_name='crimespot', name='occurrence_datetime', field=models.DateTimeField(blank=True, null=True)),
                migrations.AddField(model_name='finalverdict', name='a_final_number', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='finalverdict', name='abeted_summary_no', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='finalverdict', name='b_final_number', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='finalverdict', name='c_final_number', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='finalverdict', name='charge_sheet_no', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='finalverdict', name='nc_final_number', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AddField(model_name='finalverdict', name='quashed_by_high_court_date', field=models.DateField(blank=True, null=True)),
                migrations.AddField(model_name='finalverdict', name='stay_by_high_court_date', field=models.DateField(blank=True, null=True)),
                migrations.AddField(model_name='scrutinypipeline', name='addl_cp_grant_date', field=models.DateField(blank=True, null=True)),
                migrations.AddField(model_name='scrutinypipeline', name='addl_cp_send_date', field=models.DateField(blank=True, null=True)),
                migrations.AddField(model_name='scrutinypipeline', name='addl_sp_dcp_grant_date', field=models.DateField(blank=True, null=True)),
                migrations.AddField(model_name='scrutinypipeline', name='addl_sp_dcp_send_date', field=models.DateField(blank=True, null=True)),
                migrations.AddField(model_name='scrutinypipeline', name='sdpo_acp_grant_date', field=models.DateField(blank=True, null=True)),
                migrations.AddField(model_name='scrutinypipeline', name='sdpo_acp_send_date', field=models.DateField(blank=True, null=True)),

                # Alter fields
                migrations.AlterField(model_name='act', name='act_name', field=models.CharField(default='', max_length=100)),
                migrations.AlterField(model_name='act', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now)),
                migrations.AlterField(model_name='actsection', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now)),
                migrations.AlterField(model_name='actsection', name='section_number', field=models.CharField(default='', max_length=10)),
                migrations.AlterField(model_name='actsubsection', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now)),
                migrations.AlterField(model_name='actsubsection', name='subsection_code', field=models.CharField(default='', max_length=20)),
                migrations.AlterField(model_name='arrestreleasestatus', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now)),
                migrations.AlterField(model_name='arrestreleasestatus', name='person', field=models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, related_name='arrest_status', to='crimetab.casesperson')),
                migrations.AlterField(model_name='casesperson', name='aadhaar', field=models.CharField(blank=True, max_length=12, null=True)),
                migrations.AlterField(model_name='casesperson', name='caste', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AlterField(model_name='casesperson', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now)),
                migrations.AlterField(model_name='casesperson', name='gender', field=models.CharField(blank=True, max_length=10, null=True)),
                migrations.AlterField(model_name='casesperson', name='mobile', field=models.CharField(blank=True, max_length=10, null=True)),
                migrations.AlterField(model_name='casesperson', name='name', field=models.CharField(blank=True, max_length=150, null=True)),
                migrations.AlterField(model_name='casesperson', name='occupation', field=models.CharField(blank=True, max_length=100, null=True)),
                migrations.AlterField(model_name='casesperson', name='pan', field=models.CharField(blank=True, max_length=10, null=True)),
                migrations.AlterField(model_name='casesperson', name='religion', field=models.CharField(blank=True, max_length=50, null=True)),
                migrations.AlterField(model_name='casesperson', name='role', field=models.CharField(choices=[('complainant', 'Complainant'), ('accused', 'Accused'), ('suspected_accused', 'Suspected Accused'), ('unidentified_accused', 'Unidentified Accused')], default='accused', max_length=20)),
                migrations.AlterField(model_name='crimecaseactssections', name='act', field=models.ForeignKey(db_column='act_id', on_delete=django.db.models.deletion.CASCADE, related_name='case_charges', to='crimetab.act')),
                migrations.AlterField(model_name='crimecaseactssections', name='case', field=models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='cases.caserecord')),
                migrations.AlterField(model_name='crimecaseactssections', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now)),
                migrations.AlterField(model_name='crimecaseactssections', name='section', field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='case_charges', to='crimetab.actsection')),
                migrations.AlterField(model_name='crimecaseresponsibility', name='case', field=models.OneToOneField(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='responsibility', serialize=False, to='cases.caserecord')),
                migrations.AlterField(model_name='crimecaseresponsibility', name='io_designation', field=models.CharField(blank=True, max_length=20, null=True)),
                migrations.AlterField(model_name='crimecaseresponsibility', name='io_name', field=models.CharField(blank=True, max_length=150, null=True)),
                migrations.AlterField(model_name='crimecaseresponsibility', name='registered_by_designation', field=models.CharField(blank=True, max_length=20, null=True)),
                migrations.AlterField(model_name='crimecaseresponsibility', name='registered_by_name', field=models.CharField(blank=True, max_length=150, null=True)),
                migrations.AlterField(model_name='crimeregistrationinfo', name='case', field=models.OneToOneField(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registration_info', serialize=False, to='cases.caserecord')),
                migrations.AlterField(model_name='crimeregistrationinfo', name='created_at', field=models.DateTimeField(default=django.utils.timezone.now)),
                migrations.AlterField(model_name='crimeregistrationinfo', name='updated_at', field=models.DateTimeField(default=django.utils.timezone.now)),
                migrations.AlterField(model_name='crimespot', name='area_name', field=models.CharField(blank=True, max_length=100, null=True)),
                migrations.AlterField(model_name='crimespot', name='case', field=models.OneToOneField(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spot', serialize=False, to='cases.caserecord')),
                migrations.AlterField(model_name='crimespot', name='village_town', field=models.CharField(blank=True, max_length=100, null=True)),
                migrations.AlterField(model_name='dischargestatus', name='is_discharged', field=models.BooleanField(default=True)),
                migrations.AlterField(model_name='dischargestatus', name='person', field=models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='discharge_status', serialize=False, to='crimetab.casesperson')),
                migrations.AlterField(model_name='finalverdict', name='case', field=models.OneToOneField(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='final_verdict', serialize=False, to='cases.caserecord')),
                migrations.AlterField(model_name='scrutinypipeline', name='case', field=models.OneToOneField(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scrutiny_pipeline', serialize=False, to='cases.caserecord')),
                migrations.AlterField(model_name='sectionfieldtemplate', name='section', field=models.ForeignKey(blank=True, db_column='section_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_mappings', to='crimetab.actsection')),

                # Indexes & Constraints
                migrations.AddIndex(model_name='casesperson', index=models.Index(fields=['case'], name='idx_person_case')),
                migrations.AddIndex(model_name='casesperson', index=models.Index(fields=['case', 'role'], name='idx_person_case_role')),
                migrations.AddIndex(model_name='crimecaseactssections', index=models.Index(fields=['case'], name='idx_charges_case')),
                migrations.AddIndex(model_name='crimecaseactssections', index=models.Index(fields=['section'], name='idx_charges_section')),
                migrations.AddConstraint(
                    model_name='remandcustody',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('pr_bond__isnull', True), ('pr_bond', False), _connector='OR'), ('mcr', True), _connector='OR'), name='chk_pr_bond_requires_mcr'),
                ),
                migrations.AddConstraint(
                    model_name='remandcustody',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('surety_name__isnull', True), ('surety_name', ''), _connector='OR'), models.Q(('jail__isnull', True), ('jail', False), _connector='OR')), ('bail', True), _connector='OR'), name='chk_surety_jail_requires_bail'),
                ),
            ],
        ),
    ]
