# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0004_caseforensics_cctvtechnical_preventiveactionitems_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS category_field_templates (
                        id              BIGSERIAL PRIMARY KEY,
                        category_id     BIGINT NOT NULL REFERENCES case_categories(category_id) ON DELETE CASCADE,
                        template_id     BIGINT NOT NULL REFERENCES field_templates(template_id) ON DELETE CASCADE,
                        UNIQUE (category_id, template_id)
                    );
                    CREATE INDEX IF NOT EXISTS idx_cat_field_tmpl_cat ON category_field_templates(category_id);
                    CREATE INDEX IF NOT EXISTS idx_cat_field_tmpl_tmpl ON category_field_templates(template_id);
                    """,
                    reverse_sql="""
                    DROP TABLE IF EXISTS category_field_templates CASCADE;
                    """
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CategoryFieldTemplate',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('category', models.ForeignKey(
                            db_column='category_id',
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='category_template_mappings',
                            to='crimetab.casecategory'
                        )),
                        ('template', models.ForeignKey(
                            db_column='template_id',
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='category_mappings',
                            to='crimetab.fieldtemplate'
                        )),
                    ],
                    options={
                        'verbose_name': 'Category Field Template',
                        'verbose_name_plural': 'Category Field Templates',
                        'db_table': 'category_field_templates',
                        'unique_together': {('category', 'template')},
                    },
                ),
            ]
        ),
    ]
