# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0005_categoryfieldtemplate_alter_act_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE seizure_records
                        ADD COLUMN IF NOT EXISTS seized_from_person_id BIGINT REFERENCES cases_person(person_id) ON DELETE SET NULL;
                    CREATE INDEX IF NOT EXISTS idx_seizure_person ON seizure_records(seized_from_person_id);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS idx_seizure_person;
                    ALTER TABLE seizure_records
                        DROP COLUMN IF EXISTS seized_from_person_id;
                    """
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='seizurerecords',
                    name='seized_from_person',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='seized_from_person_id',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='seizures',
                        to='crimetab.casesperson'
                    ),
                ),
            ]
        ),
    ]
