# Generated by Django on 2026-09-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0006_alter_act_options_alter_actsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionfieldtemplate',
            name='section',
            field=models.ForeignKey(
                db_column='section_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='section_mappings',
                to='crimetab.actsection'
            ),
        ),
    ]
