# Generated by Django 6.1 on 2026-09-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0008_alter_act_options_alter_actsection_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE field_template_fields ADD COLUMN IF NOT EXISTS section VARCHAR(100);
                    ALTER TABLE seizure_records ADD COLUMN IF NOT EXISTS object_name VARCHAR(255);
                    """,
                    reverse_sql=""
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='fieldtemplatefield',
                    name='section',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='seizurerecords',
                    name='object_name',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
            ]
        ),
    ]
