# Generated by Django 6.1 on 2026-09-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0009_fieldtemplatefield_section_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE discharge_status ADD COLUMN IF NOT EXISTS discharge_date DATE;
                    ALTER TABLE discharge_status ADD COLUMN IF NOT EXISTS discharge_reason TEXT;
                    """,
                    reverse_sql=""
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='dischargestatus',
                    name='discharge_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='dischargestatus',
                    name='discharge_reason',
                    field=models.TextField(blank=True, null=True),
                ),
            ]
        ),
    ]
