# Generated by Django 6.1.1 on 2026-10-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0014_clean_scrutiny_verdict_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalverdict',
            name='cc_st_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
