# Generated by Django 6.1 on 2026-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0019_add_bail_surety_fields_to_remand_custody'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventiveactionitems',
            name='bond_cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventiveactionitems',
            name='bond_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casesperson',
            name='role',
            field=models.CharField(choices=[('complainant', 'Complainant'), ('accused', 'Accused'), ('suspected_accused', 'Suspected Accused'), ('unidentified_accused', 'Unidentified Accused'), ('unidentified', 'Unidentified'), ('unknown_accused', 'Unknown Accused'), ('victim', 'Victim'), ('deceased', 'Deceased'), ('injured', 'Injured')], default='accused', max_length=30),
        ),
    ]
