# Generated by Django 6.1.1 on 2026-10-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0015_finalverdict_cc_st_number'),
        ('crimetab', '0020_preventiveactionitems_bond_cancellation_date_and_more'),
    ]

    operations = [
    ]
