# Generated by Django for dropping deprecated/orphaned tables from both public and tenant schemas
from django.db import migrations

SQL_DROP_DEPRECATED_TABLES = """
DO $$
DECLARE
    target_schemas TEXT[] := ARRAY['public', 'maharashtra', 'manipur', 'bihar'];
    target_tables TEXT[] := ARRAY[
        'court_filing',
        'recovered_property',
        'stolen_property',
        'technical_custody',
        'preventive_actions',
        'procedural_details',
        'case_transfers',
        'district_admins',
        'super_admins',
        'users_notificationrecord',
        'users_transferrequest'
    ];
    s TEXT;
    t TEXT;
BEGIN
    -- 1. Loop through target schemas and safely drop each deprecated table if present
    FOREACH s IN ARRAY target_schemas
    LOOP
        IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = s) THEN
            FOREACH t IN ARRAY target_tables
            LOOP
                EXECUTE format('DROP TABLE IF EXISTS %I.%I CASCADE;', s, t);
            END LOOP;
        END IF;
    END LOOP;

    -- 2. Direct drop in current search_path as fallback
    FOREACH t IN ARRAY target_tables
    LOOP
        EXECUTE format('DROP TABLE IF EXISTS %I CASCADE;', t);
    END LOOP;
END
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0020_preventiveactionitems_bond_cancellation_date_and_more'),
        ('stations', '0002_district_superadmin_policestation_district_name_and_more'),
        ('users', '0008_officerprofile_is_biometric_enabled'),
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL_DROP_DEPRECATED_TABLES,
            reverse_sql="",
        ),
    ]
