# Generated by Django 6.1 on 2026-10-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimetab', '0032_add_rti_target_category_code_setting'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='rtiapplication',
                    name='status',
                    field=models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(
                                models.Q(('replied_date__isnull', False), ('rejected_date__isnull', False), models.Q(('transferred_to__isnull', False), models.Q(('transferred_to', ''), _negated=True)), _connector='OR'),
                                then=models.Value('Disposal')
                            ),
                            default=models.Value('Pending'),
                            output_field=models.CharField(max_length=10)
                        ),
                        output_field=models.CharField(max_length=10)
                    ),
                ),
            ]
        ),
    ]

