// lib/utils/state_language_helper.dart
// Maps Indian states to their majority spoken languages to automatically pre-select language/locale.

class StateLanguageHelper {
  static const Map<String, String> stateToLanguageCode = {
    'Andhra Pradesh': 'te',
    'Arunachal Pradesh': 'en',
    'Assam': 'en',
    'Bihar': 'hi',
    'Chhattisgarh': 'hi',
    'Goa': 'mr',
    'Gujarat': 'gu',
    'Haryana': 'hi',
    'Himachal Pradesh': 'hi',
    'Jharkhand': 'hi',
    'Karnataka': 'kn',
    'Kerala': 'ml',
    'Madhya Pradesh': 'hi',
    'Maharashtra': 'mr',
    'Manipur': 'en',
    'Meghalaya': 'en',
    'Mizoram': 'en',
    'Nagaland': 'en',
    'Odisha': 'en',
    'Punjab': 'pa',
    'Rajasthan': 'hi',
    'Sikkim': 'en',
    'Tamil Nadu': 'ta',
    'Telangana': 'te',
    'Tripura': 'bn',
    'Uttar Pradesh': 'hi',
    'Uttarakhand': 'hi',
    'West Bengal': 'bn',
  };

  /// Returns the language code for a given state name. Fallbacks to 'en'.
  static String getLanguageCodeForState(String stateName) {
    final normalized = stateName.trim();
    return stateToLanguageCode[normalized] ?? 'en';
  }
}

class MenuLocalizations {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'adminPanel': 'Admin Panel',
      'sendAlertsState': 'Send State Alert & Reminders',
      'sendAlertsDistrict': 'Send District Alert & Reminders',
      'sendReminderIO': 'Send Reminder to IO',
      'myCases': 'My Cases',
      'switchStation': 'Switch Policestation',
      'crimeAnalytics': 'Crime Analytics & Performance',
      'pendingTransfers': 'Pending Transfers',
      'pendingPiTransfers': 'Pending PI Transfers',
      'accessGrants': 'Dashboard access grants',
      'assignOfficer': 'Assign Officer',
      'reset': 'Reset',
      'totalCases': 'Total Cases',
      'pendingCases': 'Pending Cases',
      'disposalCases': 'Disposal Cases',
      'caseVisibility': 'Case visibility',
    },
    'mr': {
      'adminPanel': 'प्रशासकीय पॅनेल',
      'sendAlertsState': 'राज्य चेतावणी आणि स्मरणपत्रे पाठवा',
      'sendAlertsDistrict': 'जिल्हा चेतावणी आणि स्मरणपत्रे पाठवा',
      'sendReminderIO': 'तपास अधिकाऱ्याला स्मरणपत्र पाठवा',
      'myCases': 'माझे खटले',
      'switchStation': 'पोलीस ठाणे बदला',
      'crimeAnalytics': 'गुन्हे विश्लेषण आणि कामगिरी',
      'pendingTransfers': 'प्रलंबित बदल्या',
      'pendingPiTransfers': 'प्रलंबित पीआय बदल्या',
      'accessGrants': 'डॅशबोर्ड प्रवेश मंजुरी',
      'assignOfficer': 'अधिकारी नियुक्त करा',
      'reset': 'रिसेट करा',
      'totalCases': 'एकूण खटले',
      'pendingCases': 'प्रलंबित खटले',
      'disposalCases': 'विल्हेवाट लावलेले खटले',
      'caseVisibility': 'खटला दृश्यमानता',
    },
    'hi': {
      'adminPanel': 'प्रशासन पैनल',
      'sendAlertsState': 'राज्य अलर्ट और अनुस्मारक भेजें',
      'sendAlertsDistrict': 'जिला अलर्ट और अनुस्मारक भेजें',
      'sendReminderIO': 'जांच अधिकारी को अनुस्मारक भेजें',
      'myCases': 'मेरे मामले',
      'switchStation': 'पुलिस थाना बदलें',
      'crimeAnalytics': 'अपराध विश्लेषण और प्रदर्शन',
      'pendingTransfers': 'لंबित स्थानांतरण',
      'pendingPiTransfers': 'लंबित पीआई स्थानांतरण',
      'accessGrants': 'डैशबोर्ड पहुंच स्वीकृति',
      'assignOfficer': 'अधिकारी नियुक्त करें',
      'reset': 'रीसेट करें',
      'totalCases': 'कुल मामले',
      'pendingCases': 'लंबित मामले',
      'disposalCases': 'निपटाए गए मामले',
      'caseVisibility': 'मामले की दृश्यता',
    },
    'gu': {
      'adminPanel': 'વહીવટી પેનલ',
      'sendAlertsState': 'રાજ્ય ચેતવણી અને રીમાઇન્ડર્સ મોકলো',
      'sendAlertsDistrict': 'જિલ્લા ચેતવણી અને રીમાઇન્ડર્સ મોકલો',
      'sendReminderIO': 'તપાસ અધિકારીને રીમાઇન્ડર મોકলো',
      'myCases': 'મારા કેસ',
      'switchStation': 'પોલીસ સ્ટેશન બદલો',
      'crimeAnalytics': 'ગુના વિશ્લેષણ અને કામગીરી',
      'pendingTransfers': 'બાકી બદલીઓ',
      'pendingPiTransfers': 'બાકી પીઆઈ બદલીઓ',
      'accessGrants': 'ડેશબોર્ડ પ્રવેશ મંજૂરી',
      'assignOfficer': 'અધિકારી નિયુક્ત કરો',
      'reset': 'રીસેટ કરો',
      'totalCases': 'કુલ કેસ',
      'pendingCases': 'બાકી કેસ',
      'disposalCases': 'નિકાલ કરેલા કેસ',
      'caseVisibility': 'કેસ દૃશ્યતા',
    },
    'ta': {
      'adminPanel': 'நிர்வாக குழு',
      'sendAlertsState': 'மாநில எச்சரிக்கைகள் & நினைவூட்டல்களை அனுப்புக',
      'sendAlertsDistrict': 'மாவட்ட எச்சரிக்கைகள் & நினைவூட்டல்களை அனுப்புக',
      'sendReminderIO': 'விசாரணை அதிகாரிக்கு நினைவூட்டல் அனுப்புக',
      'myCases': 'எனது வழக்குகள்',
      'switchStation': 'காவல் நிலையத்தை மாற்றவும்',
      'crimeAnalytics': 'குற்ற பகுப்பாய்வு & செயல்திறன்',
      'pendingTransfers': 'நிலுவையில் உள்ள இடமாற்றங்கள்',
      'pendingPiTransfers': 'நிலுவையில் உள்ள பிஐ இடமாற்றங்கள்',
      'accessGrants': 'டாஷ்போர்டு அணுகல் அனுமதிகள்',
      'assignOfficer': 'அதிகாரியை நியமிக்கவும்',
      'reset': 'மீட்டமை',
      'totalCases': 'மொத்த வழக்குகள்',
      'pendingCases': 'நிலுவை வழக்குகள்',
      'disposalCases': 'தீர்க்கப்பட்ட வழக்குகள்',
      'caseVisibility': 'வழக்கு தெரிவுநிலை',
    },
    'te': {
      'adminPanel': 'పరిపాలన ప్యానెల్',
      'sendAlertsState': 'రాష్ట్ర అలర్ట్‌లు & రిమైండర్‌లను పంపండి',
      'sendAlertsDistrict': 'జిల్లా అలర్ట్‌లు & రిమైండర్‌లను పంపండి',
      'sendReminderIO': 'ఐఓకు రిమైండర్ పంపండి',
      'myCases': 'నా కేసులు',
      'switchStation': 'పోలీస్ స్టేషన్ మార్చండి',
      'crimeAnalytics': 'నేర విశ్లేషణ & పనితీరు',
      'pendingTransfers': 'పెండింగ్ బదిలీలు',
      'pendingPiTransfers': 'పెండింగ్ పీఐ బదిలీలు',
      'accessGrants': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ యాక్సెస్ మంజూరు',
      'assignOfficer': 'అధికారిని కేటాయించండి',
      'reset': 'రీసెట్',
      'totalCases': 'మొత్తం కేసులు',
      'pendingCases': 'పెండింగ్ కేసులు',
      'disposalCases': 'పరిష్కరించబడిన కేసులు',
      'caseVisibility': 'కేసు దృశ్యమానత',
    },
    'kn': {
      'adminPanel': 'ಆಡಳಿತ ಮಂಡಳಿ',
      'sendAlertsState': 'ರಾಜ್ಯ ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಜ್ಞಾಪನೆಗಳನ್ನು ಕಳುಹಿಸಿ',
      'sendAlertsDistrict': 'ಜಿಲ್ಲಾ ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಜ್ಞಾಪನೆಗಳನ್ನು ಕಳುಹಿಸಿ',
      'sendReminderIO': 'ಐಓಗೆ ಜ್ಞಾಪನೆ ಕಳುಹಿಸಿ',
      'myCases': 'ನನ್ನ ಪ್ರಕರಣಗಳು',
      'switchStation': 'ಪೊಲೀಸ್ ಠಾಣೆ ಬದಲಾಯಿಸಿ',
      'crimeAnalytics': 'ಅಪರಾಧ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಪ್ರದರ್ಶನ',
      'pendingTransfers': 'ಬಾಕಿ ಇರುವ ವರ್ಗಾವಣೆಗಳು',
      'pendingPiTransfers': 'ಬಾಕಿ ಇರುವ ಪಿಐ ವರ್ಗಾವಣೆಗಳು',
      'accessGrants': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶ ಮಂಜೂರಾತಿ',
      'assignOfficer': 'ಅಧಿಕಾರಿಯನ್ನು ನೇಮಿಸಿ',
      'reset': 'ಮರುಹೊಂದಿಸಿ',
      'totalCases': 'ಒಟ್ಟು ಪ್ರಕರಣಗಳು',
      'pendingCases': 'ಬಾಕಿ ಪ್ರಕರಣಗಳು',
      'disposalCases': 'ವಿಲೇವಾರಿ ಪ್ರಕರಣಗಳು',
      'caseVisibility': 'ಪ್ರಕರಣದ ಗೋಚರತೆ',
    },
    'ml': {
      'adminPanel': 'അഡ്മിൻ പാനൽ',
      'sendAlertsState': 'സംസ്ഥാന അലേർട്ടുകളും ഓർമ്മപ്പെടുത്തലുകളും അയക്കുക',
      'sendAlertsDistrict': 'ജില്ലാ അലേർട്ടുകളും ഓർമ്മപ്പെടുത്തലുകളും അയക്കുക',
      'sendReminderIO': 'ഐഒയ്ക്ക് ഓർമ്മപ്പെടുത്തൽ അയക്കുക',
      'myCases': 'എന്റെ കേസുകൾ',
      'switchStation': 'പോലീസ് സ്റ്റേഷൻ മാറ്റുക',
      'crimeAnalytics': 'കുറ്റകൃത്യ വിശകലനവും പ്രകടനവും',
      'pendingTransfers': 'തീർപ്പാക്കാത്ത കൈമാറ്റങ്ങൾ',
      'pendingPiTransfers': 'തീർപ്പാക്കാത്ത പിഐ കൈമാറ്റങ്ങൾ',
      'accessGrants': 'ഡാഷ്‌ബോർഡ് ആക്‌സസ് അനുമതികൾ',
      'assignOfficer': 'ഉദ്യോഗസ്ഥനെ നിയമിക്കുക',
      'reset': 'റീസെറ്റ് ചെയ്യുക',
      'totalCases': 'ആകെ കേസുകൾ',
      'pendingCases': 'തീർപ്പാക്കാത്ത കേസുകൾ',
      'disposalCases': 'തീർപ്പാക്കിയ കേസുകൾ',
      'caseVisibility': 'കേസ് ദൃശ്യത',
    },
    'pa': {
      'adminPanel': 'ਪ੍ਰਸ਼ਾਸਨ ਪੈਨਲ',
      'sendAlertsState': 'ਸੂਬਾ ਅਲਰਟ ਅਤੇ ਰੀਮਾਈਂਡਰ ਭੇਜੋ',
      'sendAlertsDistrict': 'ਜ਼ਿਲ੍ਹਾ ਅਲਰਟ ਅਤੇ ਰੀਮਾਈਂਡਰ ਭੇਜੋ',
      'sendReminderIO': 'ਆਈਓ ਨੂੰ ਰੀਮਾਈਂਡਰ ਭੇਜੋ',
      'myCases': 'ਮੇਰੇ ਕੇਸ',
      'switchStation': 'ਥਾਣਾ ਬਦਲੋ',
      'crimeAnalytics': 'ਅਪਰਾਧ ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਪ੍ਰਦਰਸ਼ਨ',
      'pendingTransfers': 'ਲੰਬਿਤ ਤਬਾਦਲੇ',
      'pendingPiTransfers': 'ਲੰਬਿਤ ਪੀਆਈ ਤਬਾਦਲੇ',
      'accessGrants': 'ਡੈਸ਼ਬੋਰਡ ਪਹੁੰਚ ਮਨਜ਼ੂਰੀ',
      'assignOfficer': 'ਅਧਿਕਾਰੀ ਨਿਯੁਕਤ ਕਰੋ',
      'reset': 'ਰੀਸੈਟ ਕਰੋ',
      'totalCases': 'ਕੁੱਲ ਕੇਸ',
      'pendingCases': 'ਲੰਬਿਤ ਕੇਸ',
      'disposalCases': 'ਨਿਪਟਾਏ ਗਏ ਕੇਸ',
      'caseVisibility': 'ਕੇਸ ਦੀ ਦਿੱਖ',
    },
    'bn': {
      'adminPanel': 'প্রশাসনিক প্যানেল',
      'sendAlertsState': 'রাজ্য সতর্কতা ও অনুস্মারক পাঠান',
      'sendAlertsDistrict': 'জেলা সতর্কতা ও অনুস্মারক পাঠান',
      'sendReminderIO': 'তদন্তকারী কর্মকর্তাকে অনুস্মারক পাঠান',
      'myCases': 'আমার মামলা সমূহ',
      'switchStation': 'থানা পরিবর্তন করুন',
      'crimeAnalytics': 'অপরাধ বিশ্লেষণ ও কর্মক্ষমতা',
      'pendingTransfers': 'মুলতুবি স্থানান্তর',
      'pendingPiTransfers': 'মুলতুবি পিআই স্থানান্তর',
      'accessGrants': 'ড্যাশবোর্ড অ্যাক্সেস মঞ্জুরি',
      'assignOfficer': 'কর্মকর্তা নিয়োগ করুন',
      'reset': 'রিসেট করুন',
      'totalCases': 'মোট মামলা',
      'pendingCases': 'মুলতুবি মামলা',
      'disposalCases': 'নিস্পত্তি মামলা',
      'caseVisibility': 'মামলার দৃশ্যমানতা',
    },
  };

  static String get(String langCode, String key) {
    return _localizedStrings[langCode]?[key] ?? _localizedStrings['en']![key]!;
  }
}
