# Generated by Django 6.1 on 2026-08-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('station_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255, unique=True)),
                ('district', models.CharField(blank=True, max_length=128)),
                ('zone', models.CharField(blank=True, max_length=128)),
                ('address', models.TextField(blank=True)),
                ('landline', models.CharField(blank=True, max_length=32)),
                ('pi_in_charge', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Police Station',
                'verbose_name_plural': 'Police Stations',
                'db_table': 'stations_policestation',
                'ordering': ['station_name'],
            },
        ),
    ]
